-- 커뮤니티 일자리 게시판을 위한 사용자 구인글 필드와 관광인 채용정보 캐시를 추가합니다.

ALTER TABLE public.posts
  ADD COLUMN IF NOT EXISTS job_wage_type TEXT,
  ADD COLUMN IF NOT EXISTS job_wage_amount NUMERIC(14, 2),
  ADD COLUMN IF NOT EXISTS job_working_time TEXT,
  ADD COLUMN IF NOT EXISTS job_recruitment_deadline DATE,
  ADD COLUMN IF NOT EXISTS job_is_always_recruiting BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.posts
  DROP CONSTRAINT IF EXISTS posts_job_fields_check;

ALTER TABLE public.posts
  ADD CONSTRAINT posts_job_fields_check CHECK (
    category = 'job'
    OR (
      job_wage_type IS NULL
      AND job_wage_amount IS NULL
      AND job_working_time IS NULL
      AND job_recruitment_deadline IS NULL
      AND job_is_always_recruiting = FALSE
    )
  );

CREATE OR REPLACE FUNCTION public.clear_non_job_post_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.category <> 'job' THEN
    NEW.job_wage_type := NULL;
    NEW.job_wage_amount := NULL;
    NEW.job_working_time := NULL;
    NEW.job_recruitment_deadline := NULL;
    NEW.job_is_always_recruiting := FALSE;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS clear_non_job_post_fields_trigger ON public.posts;
CREATE TRIGGER clear_non_job_post_fields_trigger
  BEFORE INSERT OR UPDATE OF category, job_wage_type, job_wage_amount,
    job_working_time, job_recruitment_deadline, job_is_always_recruiting
  ON public.posts
  FOR EACH ROW
  EXECUTE FUNCTION public.clear_non_job_post_fields();

CREATE INDEX IF NOT EXISTS idx_posts_job_region_created_at
  ON public.posts(upper_region, lower_region, created_at DESC)
  WHERE category = 'job';

CREATE TABLE IF NOT EXISTS public.tour_api_region_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  upper_region TEXT NOT NULL,
  lower_region TEXT NOT NULL,
  regn_cd TEXT NOT NULL,
  signgu_cd TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT tour_api_region_mappings_region_key
    UNIQUE (upper_region, lower_region),
  CONSTRAINT tour_api_region_mappings_code_key
    UNIQUE (regn_cd, signgu_cd)
);

CREATE TABLE IF NOT EXISTS public.tour_api_job_postings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empmn_info_no TEXT NOT NULL UNIQUE,
  upper_region TEXT NOT NULL,
  lower_region TEXT NOT NULL,
  regn_cd TEXT NOT NULL,
  signgu_cd TEXT NOT NULL,
  company_name TEXT,
  title TEXT NOT NULL,
  workplace TEXT,
  salary TEXT,
  wage_type TEXT,
  employment_type TEXT,
  career_condition TEXT,
  recruitment_count TEXT,
  working_time TEXT,
  recruitment_deadline DATE,
  is_always_recruiting BOOLEAN NOT NULL DEFAULT FALSE,
  show_yn BOOLEAN NOT NULL DEFAULT TRUE,
  registered_at TIMESTAMPTZ,
  modified_at TIMESTAMPTZ,
  original_url TEXT,
  basic_payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  detail_payload JSONB,
  detail_fetched_at TIMESTAMPTZ,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tour_api_job_postings_region_status
  ON public.tour_api_job_postings(
    upper_region,
    lower_region,
    show_yn,
    is_always_recruiting,
    recruitment_deadline,
    registered_at DESC
  );

ALTER TABLE public.tour_api_region_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tour_api_job_postings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Tour API region mappings are viewable by authenticated users."
  ON public.tour_api_region_mappings;
CREATE POLICY "Tour API region mappings are viewable by authenticated users."
  ON public.tour_api_region_mappings FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Tour API job postings are viewable by authenticated users."
  ON public.tour_api_job_postings;
CREATE POLICY "Tour API job postings are viewable by authenticated users."
  ON public.tour_api_job_postings FOR SELECT
  TO authenticated
  USING (show_yn = TRUE);

GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT ON public.tour_api_region_mappings TO authenticated;
GRANT SELECT ON public.tour_api_job_postings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tour_api_region_mappings TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tour_api_job_postings TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.tour_api_region_mappings_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.tour_api_job_postings_id_seq TO service_role;
REVOKE ALL ON public.tour_api_region_mappings FROM anon;
REVOKE ALL ON public.tour_api_job_postings FROM anon;
REVOKE INSERT, UPDATE, DELETE ON public.tour_api_region_mappings FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.tour_api_job_postings FROM authenticated;

-- 클라이언트가 게시물 작성자 ID나 일자리 전용 컬럼을 직접 조작하지 않도록 서버 RPC로 저장합니다.
CREATE OR REPLACE FUNCTION public.create_job_post_with_images(
  p_upper_region TEXT,
  p_lower_region TEXT,
  p_title TEXT,
  p_content TEXT,
  p_images JSONB DEFAULT '[]'::JSONB,
  p_place_name TEXT DEFAULT NULL,
  p_place_latitude DOUBLE PRECISION DEFAULT NULL,
  p_place_longitude DOUBLE PRECISION DEFAULT NULL,
  p_place_address TEXT DEFAULT NULL,
  p_place_road_address TEXT DEFAULT NULL,
  p_place_category TEXT DEFAULT NULL,
  p_job_wage_type TEXT DEFAULT NULL,
  p_job_wage_amount NUMERIC DEFAULT NULL,
  p_job_working_time TEXT DEFAULT NULL,
  p_job_recruitment_deadline DATE DEFAULT NULL,
  p_job_is_always_recruiting BOOLEAN DEFAULT FALSE
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_account_id UUID := public.current_account_id();
  v_post_id UUID;
  v_image JSONB;
BEGIN
  IF v_account_id IS NULL THEN
    RAISE EXCEPTION 'Authenticated account is required';
  END IF;

  IF NULLIF(BTRIM(p_upper_region), '') IS NULL
    OR NULLIF(BTRIM(p_lower_region), '') IS NULL THEN
    RAISE EXCEPTION '게시 지역을 입력해주세요.';
  END IF;

  IF NULLIF(BTRIM(p_title), '') IS NULL THEN
    RAISE EXCEPTION '제목을 입력해주세요.';
  END IF;

  IF NULLIF(BTRIM(p_content), '') IS NULL THEN
    RAISE EXCEPTION '내용을 입력해주세요.';
  END IF;

  IF CHAR_LENGTH(BTRIM(p_title)) > 50 THEN
    RAISE EXCEPTION '제목은 50자 이내로 입력해주세요.';
  END IF;

  IF CHAR_LENGTH(BTRIM(p_content)) > 10000 THEN
    RAISE EXCEPTION '본문은 10,000자 이내로 입력해주세요.';
  END IF;

  IF p_job_wage_type IS NOT NULL
    AND p_job_wage_type NOT IN ('시급', '일급', '주급', '월급', '건당', '협의') THEN
    RAISE EXCEPTION '급여 형태가 올바르지 않습니다.';
  END IF;

  IF p_job_wage_amount IS NOT NULL AND p_job_wage_amount < 0 THEN
    RAISE EXCEPTION '급여 금액은 0 이상이어야 합니다.';
  END IF;

  IF p_job_is_always_recruiting = TRUE AND p_job_recruitment_deadline IS NOT NULL THEN
    RAISE EXCEPTION '상시 모집은 마감일과 함께 사용할 수 없습니다.';
  END IF;

  IF p_job_is_always_recruiting = FALSE AND p_job_recruitment_deadline IS NULL THEN
    RAISE EXCEPTION '모집 마감일 또는 상시 모집을 선택해주세요.';
  END IF;

  IF p_images IS NULL OR JSONB_TYPEOF(p_images) <> 'array'
    OR JSONB_ARRAY_LENGTH(p_images) > 10 THEN
    RAISE EXCEPTION '이미지 목록이 올바르지 않습니다.';
  END IF;

  INSERT INTO public.posts (
    author_id,
    upper_region,
    lower_region,
    category,
    title,
    content,
    place_name,
    place_latitude,
    place_longitude,
    place_address,
    place_road_address,
    place_category,
    job_wage_type,
    job_wage_amount,
    job_working_time,
    job_recruitment_deadline,
    job_is_always_recruiting
  )
  VALUES (
    v_account_id,
    BTRIM(p_upper_region),
    BTRIM(p_lower_region),
    'job',
    BTRIM(p_title),
    BTRIM(p_content),
    NULLIF(BTRIM(p_place_name), ''),
    p_place_latitude,
    p_place_longitude,
    NULLIF(BTRIM(p_place_address), ''),
    NULLIF(BTRIM(p_place_road_address), ''),
    NULLIF(BTRIM(p_place_category), ''),
    NULLIF(BTRIM(p_job_wage_type), ''),
    p_job_wage_amount,
    NULLIF(BTRIM(p_job_working_time), ''),
    p_job_recruitment_deadline,
    COALESCE(p_job_is_always_recruiting, FALSE)
  )
  RETURNING id INTO v_post_id;

  FOR v_image IN SELECT value FROM JSONB_ARRAY_ELEMENTS(p_images)
  LOOP
    IF JSONB_TYPEOF(v_image) <> 'object'
      OR NULLIF(BTRIM(v_image ->> 'storage_path'), '') IS NULL
      OR NULLIF(BTRIM(v_image ->> 'public_url'), '') IS NULL
      OR (v_image ->> 'sort_order')::INTEGER < 0
      OR SPLIT_PART(v_image ->> 'storage_path', '/', 1) <> 'accounts'
      OR SPLIT_PART(v_image ->> 'storage_path', '/', 2) <> v_account_id::TEXT THEN
      RAISE EXCEPTION '이미지 정보가 올바르지 않습니다.';
    END IF;

    INSERT INTO public.post_images (
      post_id, storage_path, public_url, sort_order
    )
    VALUES (
      v_post_id,
      BTRIM(v_image ->> 'storage_path'),
      BTRIM(v_image ->> 'public_url'),
      (v_image ->> 'sort_order')::INTEGER
    );
  END LOOP;

  RETURN v_post_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_job_post_with_images(
  p_post_id UUID,
  p_upper_region TEXT,
  p_lower_region TEXT,
  p_title TEXT,
  p_content TEXT,
  p_images JSONB DEFAULT '[]'::JSONB,
  p_place_name TEXT DEFAULT NULL,
  p_place_latitude DOUBLE PRECISION DEFAULT NULL,
  p_place_longitude DOUBLE PRECISION DEFAULT NULL,
  p_place_address TEXT DEFAULT NULL,
  p_place_road_address TEXT DEFAULT NULL,
  p_place_category TEXT DEFAULT NULL,
  p_job_wage_type TEXT DEFAULT NULL,
  p_job_wage_amount NUMERIC DEFAULT NULL,
  p_job_working_time TEXT DEFAULT NULL,
  p_job_recruitment_deadline DATE DEFAULT NULL,
  p_job_is_always_recruiting BOOLEAN DEFAULT FALSE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_account_id UUID := public.current_account_id();
  v_post_id UUID;
  v_image JSONB;
  v_removed_storage_paths TEXT[];
BEGIN
  IF v_account_id IS NULL THEN
    RAISE EXCEPTION 'Authenticated account is required';
  END IF;

  IF p_images IS NULL OR JSONB_TYPEOF(p_images) <> 'array'
    OR JSONB_ARRAY_LENGTH(p_images) > 10 THEN
    RAISE EXCEPTION '이미지 목록이 올바르지 않습니다.';
  END IF;

  SELECT id INTO v_post_id
  FROM public.posts
  WHERE id = p_post_id AND author_id = v_account_id AND category = 'job'
  FOR UPDATE;

  IF v_post_id IS NULL THEN
    RAISE EXCEPTION '일자리 게시글을 수정할 권한이 없습니다.';
  END IF;

  IF NULLIF(BTRIM(p_upper_region), '') IS NULL
    OR NULLIF(BTRIM(p_lower_region), '') IS NULL
    OR NULLIF(BTRIM(p_title), '') IS NULL
    OR NULLIF(BTRIM(p_content), '') IS NULL THEN
    RAISE EXCEPTION '게시 지역, 제목, 내용을 입력해주세요.';
  END IF;

  IF CHAR_LENGTH(BTRIM(p_title)) > 50 OR CHAR_LENGTH(BTRIM(p_content)) > 10000 THEN
    RAISE EXCEPTION '제목은 50자, 본문은 10,000자 이내로 입력해주세요.';
  END IF;

  IF p_job_wage_type IS NOT NULL
    AND p_job_wage_type NOT IN ('시급', '일급', '주급', '월급', '건당', '협의') THEN
    RAISE EXCEPTION '급여 형태가 올바르지 않습니다.';
  END IF;

  IF p_job_wage_amount IS NOT NULL AND p_job_wage_amount < 0 THEN
    RAISE EXCEPTION '급여 금액은 0 이상이어야 합니다.';
  END IF;

  IF p_job_is_always_recruiting = TRUE AND p_job_recruitment_deadline IS NOT NULL THEN
    RAISE EXCEPTION '상시 모집은 마감일과 함께 사용할 수 없습니다.';
  END IF;

  IF p_job_is_always_recruiting = FALSE AND p_job_recruitment_deadline IS NULL THEN
    RAISE EXCEPTION '모집 마감일 또는 상시 모집을 선택해주세요.';
  END IF;

  FOR v_image IN SELECT value FROM JSONB_ARRAY_ELEMENTS(p_images)
  LOOP
    IF JSONB_TYPEOF(v_image) <> 'object'
      OR NULLIF(BTRIM(v_image ->> 'storage_path'), '') IS NULL
      OR NULLIF(BTRIM(v_image ->> 'public_url'), '') IS NULL
      OR (v_image ->> 'sort_order') IS NULL
      OR (v_image ->> 'sort_order')::INTEGER < 0
      OR SPLIT_PART(v_image ->> 'storage_path', '/', 1) <> 'accounts'
      OR SPLIT_PART(v_image ->> 'storage_path', '/', 2) <> v_account_id::TEXT THEN
      RAISE EXCEPTION '이미지 정보가 올바르지 않습니다.';
    END IF;
  END LOOP;

  SELECT COALESCE(
    ARRAY_AGG(pi.storage_path ORDER BY pi.sort_order),
    ARRAY[]::TEXT[]
  )
  INTO v_removed_storage_paths
  FROM public.post_images pi
  WHERE pi.post_id = v_post_id
    AND NOT EXISTS (
      SELECT 1
      FROM JSONB_ARRAY_ELEMENTS(p_images) image
      WHERE image ->> 'storage_path' = pi.storage_path
    );

  IF COALESCE(ARRAY_LENGTH(v_removed_storage_paths, 1), 0) > 0 THEN
    INSERT INTO public.storage_cleanup_queue (
      account_id, bucket_id, storage_path, next_retry_at
    )
    SELECT v_account_id, 'community-images', storage_path, now()
    FROM UNNEST(v_removed_storage_paths) AS paths(storage_path)
    ON CONFLICT (account_id, bucket_id, storage_path) DO UPDATE
      SET attempt_count = 0,
          last_error = NULL,
          next_retry_at = now(),
          lease_until = NULL;
  END IF;

  UPDATE public.posts
  SET upper_region = BTRIM(p_upper_region),
      lower_region = BTRIM(p_lower_region),
      title = BTRIM(p_title),
      content = BTRIM(p_content),
      place_name = NULLIF(BTRIM(p_place_name), ''),
      place_latitude = p_place_latitude,
      place_longitude = p_place_longitude,
      place_address = NULLIF(BTRIM(p_place_address), ''),
      place_road_address = NULLIF(BTRIM(p_place_road_address), ''),
      place_category = NULLIF(BTRIM(p_place_category), ''),
      job_wage_type = NULLIF(BTRIM(p_job_wage_type), ''),
      job_wage_amount = p_job_wage_amount,
      job_working_time = NULLIF(BTRIM(p_job_working_time), ''),
      job_recruitment_deadline = p_job_recruitment_deadline,
      job_is_always_recruiting = COALESCE(p_job_is_always_recruiting, FALSE),
      updated_at = now()
  WHERE id = v_post_id;

  DELETE FROM public.post_images WHERE post_id = v_post_id;

  INSERT INTO public.post_images (
    post_id, storage_path, public_url, sort_order
  )
  SELECT
    v_post_id,
    BTRIM(image ->> 'storage_path'),
    BTRIM(image ->> 'public_url'),
    (image ->> 'sort_order')::INTEGER
  FROM JSONB_ARRAY_ELEMENTS(p_images) AS images(image);

  RETURN JSONB_BUILD_OBJECT(
    'post_id', v_post_id,
    'removed_storage_paths', TO_JSONB(v_removed_storage_paths)
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.create_job_post_with_images(
  TEXT, TEXT, TEXT, TEXT, JSONB, TEXT, DOUBLE PRECISION, DOUBLE PRECISION,
  TEXT, TEXT, TEXT, TEXT, NUMERIC, TEXT, DATE, BOOLEAN
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_job_post_with_images(
  TEXT, TEXT, TEXT, TEXT, JSONB, TEXT, DOUBLE PRECISION, DOUBLE PRECISION,
  TEXT, TEXT, TEXT, TEXT, NUMERIC, TEXT, DATE, BOOLEAN
) TO authenticated;

REVOKE EXECUTE ON FUNCTION public.update_job_post_with_images(
  UUID, TEXT, TEXT, TEXT, TEXT, JSONB, TEXT, DOUBLE PRECISION, DOUBLE PRECISION,
  TEXT, TEXT, TEXT, TEXT, NUMERIC, TEXT, DATE, BOOLEAN
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_job_post_with_images(
  UUID, TEXT, TEXT, TEXT, TEXT, JSONB, TEXT, DOUBLE PRECISION, DOUBLE PRECISION,
  TEXT, TEXT, TEXT, TEXT, NUMERIC, TEXT, DATE, BOOLEAN
) TO authenticated;
